# Generated by Django 3.0.7 on 2020-06-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('grade', models.IntegerField()),
                ('former', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EAS.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('grade', models.IntegerField()),
                ('learned_courses', models.ManyToManyField(to='EAS.Course')),
            ],
        ),
    ]
