# Generated by Django 3.0.7 on 2020-06-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAS', '0003_auto_20200627_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chosen_courses',
            field=models.ManyToManyField(related_name='chosen', to='EAS.Course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='learned_courses',
            field=models.ManyToManyField(related_name='learned', to='EAS.Course'),
        ),
    ]
